github: {
  "hostname": "github.com",
  "pages_hostname": "github.io",
  "api_url": "https://api.github.com",
  "environment": "dotcom",
  "build_revision": "8463d229ff2567d4bdc8e83fae8cf3f8219efe59",
  "project_title": "firebug.github.io",
  "project_tagline": "All things Firefox, Firebug and more",
  "owner_name": "firebug",
  "owner_url": "https://github.com/firebug",
  "owner_gravatar_url": "https://github.com/firebug.png",
  "repository_url": "https://github.com/firebug/firebug.github.io",
  "repository_nwo": "firebug/firebug.github.io",
  "repository_name": "firebug.github.io",
  "zip_url": "https://github.com/firebug/firebug.github.io/zipball/master",
  "tar_url": "https://github.com/firebug/firebug.github.io/tarball/master",
  "clone_url": "https://github.com/firebug/firebug.github.io.git",
  "releases_url": "https://github.com/firebug/firebug.github.io/releases",
  "issues_url": "https://github.com/firebug/firebug.github.io/issues",
  "wiki_url": "https://github.com/firebug/firebug.github.io/wiki",
  "language": null,
  "is_user_page": true,
  "is_project_page": false,
  "show_downloads": true,
  "url": "http://firebug.github.io"
}
